version: '3'

services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=caching_sha2_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    security_opt:
      - seccomp:unconfined
    restart: always
    networks:
      - backend-net

  prestashop:
    image: bitnami/prestashop:1.7
    ports:
      - 8080:80
    environment:
      - PRESTASHOP_DATABASE_HOST=${PRESTASHOP_DATABASE_HOST}
      - PRESTASHOP_DATABASE_USER=${PRESTASHOP_DATABASE_USER}
      - PRESTASHOP_DATABASE_NAME=${PRESTASHOP_DATABASE_NAME}
      - PRESTASHOP_DATABASE_PASSWORD=${PRESTASHOP_DATABASE_PASSWORD}
      - ALLOW_EMPTY_PASSWORD=no
      - PRESTASHOP_FIRST_NAME=${PRESTASHOP_FIRST_NAME}
      - PRESTASHOP_DATABASE_PORT_NUMBER=${PRESTASHOP_DATABASE_PORT_NUMBER}
      - PRESTASHOP_LAST_NAME=${PRESTASHOP_LAST_NAME}
      - PRESTASHOP_PASSWORD=${PRESTASHOP_PASSWORD}
      - PRESTASHOP_EMAIL=${PRESTASHOP_EMAIL}
      - PRESTASHOP_HOST=${PRESTASHOP_HOST}
      - PRESTASHOP_COUNTRY=${PRESTASHOP_COUNTRY}
      - PRESTASHOP_LANGUAGE=${PRESTASHOP_LANGUAGE}
    volumes:
      - prestashop_data:/bitnami/prestashop
    depends_on:
      - mysql
    restart: always
    networks:
      - frontend-net
      - backend-net
  phpmyadmin:
    image: phpmyadmin:5
    ports:
      - 8081:80
    depends_on:
      - mysql
    networks:
      - frontend-net
      - backend-net

volumes:
  mysql_data:
  prestashop_data:

networks:
 frontend-net:
 backend-net: