version: '3'

services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=caching_sha2_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=bitnamiROOT
      - MYSQL_DATABASE=bitnami_prestashop
      - MYSQL_USER=bn_prestashop
      - MYSQL_PASSWORD=bitnamiUSER
    volumes:
      - mysql_data:/var/lib/mysql
    security_opt:
      - seccomp:unconfined
    restart: always
    networks:
      - backend-net

  prestashop:
    ports:
      - 80:8080
    image: bitnami/prestashop:1.7
    environment:
      - PRESTASHOP_DATABASE_HOST=mysql
      - PRESTASHOP_DATABASE_USER=bn_prestashop
      - PRESTASHOP_DATABASE_NAME=bitnami_prestashop
      - PRESTASHOP_DATABASE_PASSWORD=bitnamiUSER
      - ALLOW_EMPTY_PASSWORD=no
      - PRESTASHOP_DATABASE_PORT_NUMBER=3306
      - PRESTASHOP_FIRST_NAME=samuel
      - PRESTASHOP_LAST_NAME=hernandez
      - PRESTASHOP_PASSWORD=password123 
      - PRESTASHOP_EMAIL=samuel@example.com
      - PRESTASHOP_HOST=54.152.86.90
      - PRESTASHOP_COUNTRY=es
      - PRESTASHOP_LANGUAGE=es
    volumes:
      - prestashop_data:/bitnami/prestashop
    depends_on:
      - mysql
    restart: always
    networks:
      - frontend-net
      - backend-net
  phpmyadmin:
    image: phpmyadmin:5
    ports:
      - 8080:80
    depends_on:
      - mysql
    networks:
      - frontend-net
      - backend-net
volumes:
  mysql_data:
  prestashop_data:

networks:
 frontend-net:
 backend-net:
